# This is a basic workflow to help you get started with Actions

name: test wesite

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build and deploy:
    steps:
    - name: log in to the server
      uses: actions/checkout@v3
      with:
        host: 192.168.1.105
        username: root
        password: 123
        script: pwd
