# This is a basic workflow to help you get started with Actions

name: test wesite

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on:  ubuntu-latest
    steps:
    - name: log in to the server
      uses: easingthemes/ssh-deploy@main
      with:
        host: ${{ secrets.MY_SER  }}
        username: ${{ secrets.MY_USER}}
        key:  ${{ secrets.KEY}}

    # - name: login server part2
    #   run:  >
    #     ssh ${{ secrets.MY_USER}}@${{ secrets.MY_SER  }}  "
    #     cd  /root/website &&
    #     touch testfile.txt"
